import {
  imagen0,
  imagen1,
  imagen2,
  imagen3,
  imagen4,
  imagen5,
  imagen6,
  imagen7,
  imagen8,
  imagen9,
  imagen10,
  imagen11,
  imagen12,
  imagen13,
  imagen14,
  imagen15,
  imagen16,
  imagen17,
  imagen18,
  imagen19,
  imagen20,
  imagen21,
  imagen22,
  imagen23,
  imagen24,
  imagen25,
  imagen26,
  imagen27,
  imagen28,
  imagen29,
  imagen30,
  imagen31,
  imagen32,
  imagen33,
  imagen34,
  imagen35,
  imagen36,
  imagen37,
  imagen38,
  imagen39,
  imagen40,
  imagen41,
  imagen42,
  imagen43,
} from "../assets";

export const gallery = [
  { image: imagen0, alt: "Imagen 0" },
  { image: imagen1, alt: "Imagen 1" },
  { image: imagen2, alt: "Imagen 2" },
  { image: imagen3, alt: "Imagen 3" },
  { image: imagen4, alt: "Imagen 4" },
  { image: imagen5, alt: "Imagen 5" },
  { image: imagen6, alt: "Imagen 6" },
  { image: imagen7, alt: "Imagen 7" },
  { image: imagen8, alt: "Imagen 8" },
  { image: imagen9, alt: "Imagen 9" },
  { image: imagen10, alt: "Imagen 10" },
  { image: imagen11, alt: "Imagen 11" },
  { image: imagen12, alt: "Imagen 12" },
  { image: imagen13, alt: "Imagen 13" },
  { image: imagen14, alt: "Imagen 14" },
  { image: imagen15, alt: "Imagen 15" },
  { image: imagen16, alt: "Imagen 16" },
  { image: imagen17, alt: "Imagen 17" },
  { image: imagen18, alt: "Imagen 18" },
  { image: imagen19, alt: "Imagen 19" },
  { image: imagen20, alt: "Imagen 20" },
  { image: imagen21, alt: "Imagen 21" },
  { image: imagen22, alt: "Imagen 22" },
  { image: imagen23, alt: "Imagen 23" },
  { image: imagen24, alt: "Imagen 24" },
  { image: imagen25, alt: "Imagen 25" },
  { image: imagen26, alt: "Imagen 26" },
  { image: imagen27, alt: "Imagen 27" },
  { image: imagen28, alt: "Imagen 28" },
  { image: imagen29, alt: "Imagen 29" },
  { image: imagen30, alt: "Imagen 30" },
  { image: imagen31, alt: "Imagen 31" },
  { image: imagen32, alt: "Imagen 32" },
  { image: imagen33, alt: "Imagen 33" },
  { image: imagen34, alt: "Imagen 34" },
  { image: imagen35, alt: "Imagen 35" },
  { image: imagen36, alt: "Imagen 36" },
  { image: imagen37, alt: "Imagen 37" },
  { image: imagen38, alt: "Imagen 38" },
  { image: imagen39, alt: "Imagen 39" },
  { image: imagen40, alt: "Imagen 40" },
  { image: imagen41, alt: "Imagen 41" },
  { image: imagen42, alt: "Imagen 42" },
  { image: imagen43, alt: "Imagen 43" },
];
